# Generated by Django 3.0.2 on 2020-01-30 11:23

from django.db import migrations


def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Pratik Mehta", email="pratik@email.com", document="22342342", phone="10101010").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
